Fixing 0.0.4
davidroman0O/moleculer-cron pull request #29
Opened 2024-07-11 21:47 UTC by davidroman0O

- Adjusting the API
- fixing #27 and #28
- Adding typescript types #3

2024-07-12 07:25 UTC, marceliwac commented on README.md
> +Cron mixin for Moleculer using [Node-Cron](https://github.com/kelektiv/node-cron).
You actually use [cron](https://www.npmjs.com/package/cron), not node-cron. It must have changed at some point, since the github url points to the right place.

```suggestion
Cron mixin for Moleculer using [cron](https://www.npmjs.com/package/cron).
```

2024-07-12 08:28 UTC, marceliwac requested changes
Solid work on this, thank you for the contribution! I'm not a typescript ninja so you might want to take some of these with a grain of salt 😅. 

I think there are few changes to be made; it might be worth discussing some of them if you're up for it!

2024-07-12 08:28 UTC, marceliwac commented on src/index.js
> +            if (jobConfig.OnStart) jobConfig.OnStart();
CronJobConfig does not seem to define `OnStart`, you also don't seem to implement it anywhere else.
```suggestion
```

2024-07-12 08:28 UTC, marceliwac commented on src/index.js
> +            if (jobConfig.OnStop) jobConfig.OnStop();
There is no `OnStop` in CronJobConfig, though there is `onComplete`, but that will get called after every `onTick` call, so I wouldn't add it here.

```suggestion
```

2024-07-12 08:28 UTC, marceliwac commented on index.d.ts
> +    lastDate: () => Date;
I think you're missing `setTime` here

```suggestion
    setTime: (time: CronTime) => void;
    lastDate: () => Date;
```

2024-07-12 08:28 UTC, marceliwac commented on src/index.js
> +          startJob: function() {
Are these wrappers really necessary? Wouldn't it be easier to just call the methods on the cronJob itself since it's exposed anyway? Not trying to critique your work 😅 it just seems like a lot of effort and added API.

2024-07-12 08:28 UTC, marceliwac commented on src/index.js
> +            return this.cronJob.setTime(new CronTime(time));
I would lean towards using CronTime as the parameter to this (like in above suggestion extending the CronJobConfig to add `setTime`)
```suggestion
            return this.cronJob.setTime(time);
```

2024-07-12 08:28 UTC, marceliwac commented on src/index.js
> +        }
`runOnInit` is a parameter that declares whether the cron's `onTick` function should be fired upon initialisation of the CronJob (e.g. after its constructor runs, regardless of the `start` parameter). I would probably try to keep these consistent so there is no confusion between the two APIs. If you think that ability of specifying additional function to run when the job is created, I would probably extend the API of the CronJobConfig to add it there (e.g. as `onJobInitialised`, similarly to how you wanted to add `OnStart` and `OnStopped`. 
```suggestion
```

2024-07-12 08:28 UTC, marceliwac commented on src/index.js
> +    }
Duplicate
```suggestion
```

2024-07-12 08:28 UTC, marceliwac commented on index.d.ts
> +        cronJobs?: CronJobConfig[];
Is this not in `settings`? Also, I'm not sure but shouldn't you include the `jobs` Map here too?

2024-07-12 08:31 UTC, davidroman0O commented on README.md
> +Cron mixin for Moleculer using [Node-Cron](https://github.com/kelektiv/node-cron).
Right, i need more sleep lmao

2024-07-12 16:05 UTC, davidroman0O commented on src/index.js
> +          startJob: function() {
It's fine don't worry!
Yea I wanted to have a clear scope and I have plans for "one day" :P

2024-07-12 16:07 UTC, davidroman0O commented on src/index.js
> +            return this.cronJob.setTime(new CronTime(time));
Applied

2024-07-12 16:14 UTC, davidroman0O commented on src/index.js
> +        }
very good feedback, thank you!

2024-07-12 16:17 UTC, davidroman0O commented on index.d.ts
> +        cronJobs?: CronJobConfig[];
Good catch, changed!

2024-07-12 16:18 UTC, davidroman0O commented
Applied lot of changes
Thanks to @marceliwac for all your valuable feedback and double check
I'm pretty tired these days and you were very helpful!

2024-07-17 17:28 UTC, marceliwac commented
I've ended up [forking this repository](https://gitlab.com/marceliwac/moleculer-cron) and rewriting the logic from scratch, mostly because I wanted to stick with the original CronJob API and some other stylistic choices. I've also written a fair amount of tests to try and make it a little bit more robust, but there are few things I have yet to polish, including the whole typing system and ES6/CommonJS compatibility. You are welcome to take a look and pull in whatever changes would suit you! I have of course preserved your Copyright notice and package.json contributor entry, as well as the git history that attributes other contributors.

Some notes I thought would be useful:
- I implemented the lifecycle handlers for jobs (`onStart`, `onStop`, `onInitialise`).
- I ended up passing the entire service context, rather than just the broker, both to the `onTick` and the lifecycle handlers.
- I found the hard way that initialisation that starts the jobs should happen in `events.$broker.started` rather than `started` lifecycle handler, because service does not complete the initialisation until after all the `started` lifecycle handlers have completed, meaning that if try to call any of the actions from a job that defines `runOnInit: true`, the service won't be found (including the same service that defines the crons). You can read some more about that in the comments in `src/index.ts`.
- I also updated the documentation to hopefully better explain how different parameters interact with each other and how they can be used in this mixin, including some of the more cryptic ones like `onComplete` which _"[...] might also be triggered by onTick post its run."_ and `unrefTimeout`.
- Finally, I've added few examples in both JavaScript and TypeScript to demonstrate different config options and TypeScript implementation.

I know you went slightly different way with your patch, but on the off chance that you'd like me to merge these into your repo I'm happy to submit a PR!

2024-07-17 20:52 UTC, davidroman0O commented
Oh nice! I will merge this one and you're more than welcome to submit a PR with changes!

You're are right on the start jobs on the events, maybe your future PR would contain it!

2024-07-17 20:53 UTC, merged

2024-08-07 12:46 UTC, srosset81 commented
@davidroman0O Next time this package has breaking changes (like the changes from `crons` to `settings.cronJobs`), could you please increment the [minor version](https://semver.org/) ? By default, NPM installs the latest patch version, so this broke my code. 

Thanks a lot for your work.

2024-08-07 13:12 UTC, davidroman0O commented
Yes of course, I'm sorry!!